/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SW_TOGGLE_aliases.h"
#include "SW_TOGGLE.h"
#include "LED_TOGGLE_aliases.h"
#include "LED_TOGGLE.h"
#include "IRQ_PRESS.h"
#include "PWM_MOTOR.h"
#include "CLK.h"
#include "MOTOR_aliases.h"
#include "MOTOR.h"
#include "Direction_aliases.h"
#include "Direction.h"
#include "TACHO_SENSOR_aliases.h"
#include "TACHO_SENSOR.h"
#include "LED_TACHO_aliases.h"
#include "LED_TACHO.h"
#include "PWM_TACHO.h"
#include "CLK_PWM.h"
#include "Counter_TACHO.h"
#include "CLK_CNT.h"
#include "IRQ_TACHO.h"
#include "UART_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

