/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_TX.h"
#include "UART_RX.h"
#include "I2C_DISPLAY.h"
#include "I2C_DISPLAY_PVT.h"
#include "SCL_DISPLAY_aliases.h"
#include "SCL_DISPLAY.h"
#include "SDA_DISPLAY_aliases.h"
#include "SDA_DISPLAY.h"
#include "PWM_MOTOR_SPEED.h"
#include "CLK.h"
#include "SPEED_aliases.h"
#include "SPEED.h"
#include "DIRECTION_aliases.h"
#include "DIRECTION.h"
#include "BUZZER.h"
#include "Clock_1.h"
#include "PWM_TACHO.h"
#include "CLK_PWM.h"
#include "IRQ_TACHO.h"
#include "TACHO_SENSOR_aliases.h"
#include "TACHO_SENSOR.h"
#include "LED_TACHO_aliases.h"
#include "LED_TACHO.h"
#include "Counter_TACHO.h"
#include "CLK_CNT.h"
#include "UART.h"
#include "UART_TX_IntClock.h"
#include "UART_RX_IntClock.h"
#include "I2C_DISPLAY_IntClock.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

